name: Checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: "experimental-features = nix-command flakes pipe-operators"

    - name: Build Project
      run: nix flake check
