name: Checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
      run: sudo apt-get remove -y '^ghc-8.*'
      run: sudo apt-get remove -y '^dotnet-.*'
      run: sudo apt-get remove -y '^llvm-.*'
      run: sudo apt-get remove -y 'php.*'
      run: sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
      run: sudo apt-get autoremove -y
      run: sudo apt-get clean     
      run: rm -rf /usr/share/dotnet/

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Nix
      uses: cachix/install-nix-action@v27
      with:
        install_url: https://releases.nixos.org/nix/nix-2.24.11/install
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: "experimental-features = nix-command flakes pipe-operators"

    - name: Build Project
      run: nix flake check
