name: Checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Nix
      uses: cachix/install-nix-action@v27
      with:
        install_url: https://releases.nixos.org/nix/nix-2.24.11/install
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: "experimental-features = nix-command flakes pipe-operators"

    - name: Update pacman mirrorlist
      run: nix flake update archlinux-mirrorlist

    - name: Update pacman keyring
      run: nix flake update archlinux-keyring

    - name: Build Project
      run: nix flake check
